ruby '2.6.2'
source 'https://rubygems.org'

# Middleman
gem 'middleman', '~>4.2.1'
gem 'middleman-syntax', '~> 3.0.0'
gem 'middleman-autoprefixer', '~> 2.7.0'
gem 'middleman-sprockets', '~> 4.1.0'
gem 'middleman-livereload', '~> 3.4.6'
gem 'rouge', '~> 2.0.5'
gem 'redcarpet', '~> 3.4.0'
gem 'nokogiri', '~> 1.10.1'

# Additional deps
gem 'therubyracer', '~> 0.12.3'

